---
- hosts: all
  sudo: True
  tasks:
  # ensure a hostname is set for the sensu-server
  # $PUBLIC_IP_ADDRESS is defined when the pancancer_launcher container is started
  - debug: var=group_names
  - debug: msg={{ lookup('env','SENSU_SERVER_IP_ADDRESS') }}
  - name: Build hosts file for all hosts
    sudo: True
    lineinfile: dest=/etc/hosts line="{{ lookup('env','SENSU_SERVER_IP_ADDRESS') }} sensu-server" state=present
    when: "'master' in group_names and \"{{ lookup('env','SENSU_SERVER_IP_ADDRESS') }}\" != \"\""

- hosts: master
  sudo: True
  tasks:
  - name: Disable ephemeral mount at /mnt for amazon AWS
    shell: umount /mnt
    register: umount_output
    ignore_errors: yes
    
# setup sensu-server
- hosts: sensu-server 
  sudo: True
  roles: 
    - { role: server-dependencies }
    - { role: base }
    - { role: server }
    - { role: sensu-cli }
    - { role: uchiwa }
    - { role: client, subscriptions: "\"common\"" }

- hosts: worker 
  sudo: True
  roles: 
    - { role: base }
    - { role: client, subscriptions: "\"common\",\"compute\"" }

- hosts: multi-node-master 
  sudo: True
  roles: 
    - { role: base }
    - { role: client, subscriptions: "\"common\",\"multi-node-master\"" }

- hosts: master 
  sudo: True
  roles: 
    - { role: base }
    - { role: client, subscriptions: "\"common\",\"sanger\"" }

- hosts: master
  sudo: True
  tasks:
  # this seems like the wrong place for this, but not sure what the best place for it is if we cannot redistribute 
  # with the AMI
  - name: Copy over pem key for BWA
    copy: src=/home/ubuntu/.ssh/gnostest.pem dest=/home/ubuntu/.gnos/
