---
- hosts: all
  sudo: True
  tasks:
  # ensure a hostname is set for the sensu-server
  # $PUBLIC_IP_ADDRESS is defined when the pancancer_launcher container is started
#  - debug: var=group_names
  - name: Sensu server IP address is
    debug: var={{ SENSU_SERVER_IP_ADDRESS | default("not defined") }}
  - name: Build hosts file for all hosts
    sudo: True
    lineinfile: dest=/etc/hosts line='{{ SENSU_SERVER_IP_ADDRESS | default("localhost") }} sensu-server' state=present
    when: SENSU_SERVER_IP_ADDRESS is defined

- hosts: master
  sudo: True
  tasks:
  - name: Disable ephemeral mount at /mnt for amazon AWS
    shell: umount /mnt
    register: umount_output
    ignore_errors: yes

# setup sensu-server
- hosts: sensu-server
  sudo: True
  roles:
    - { role: server-dependencies }
    - { role: base }
    - { role: server }
    - { role: sensu-cli }
    - { role: uchiwa }
    - { role: client, subscriptions: "\"common\",\"arch3-launcher\"" }

- hosts: master:worker
  sudo: True
  roles:
    - { role: base }
    - { role: client, subscriptions: "\"common\",\"compute\",\"docker\",\"arch3-worker\"" }
