# server/tasks/main.yml
---
- name: Template over redis config
  template: src=redis.json.j2 dest=/etc/sensu/conf.d/redis.json
  notify: restart redis

- name: Template over sensu api config
  template: src=api.json.j2 dest=/etc/sensu/conf.d/api.json
  notify: restart sensu server services

- name: Template over Graphite relay config
  template: src=relay.json.j2 dest=/etc/sensu/conf.d/relay.json
  notify: restart sensu server services
  when: use_grafana

- name: Template checks
  template: src=checks.json.j2 dest=/etc/sensu/conf.d/checks.json
  notify: restart sensu server services

- name: Ensure state of server services
  sudo: True
  service: name={{ item }} state=started enabled=yes
  with_items:
    - redis-server
    - sensu-server
    - sensu-api

- name: Create the directory structure needed by the Graphite relay
  file: path=/etc/sensu/extensions/{{item}} owner=root group=root mode=0755 state=directory
  when: use_grafana
  with_items:
    - mutators
    - handlers

- name: Copy over relay.rb needed by Graphite data collection
  copy: src=relay.rb dest=/etc/sensu/extensions/handlers/relay.rb mode=0644
  notify: restart sensu server services
  when: use_grafana

- name: Copy over metrics.rb needed by Graphite data collection
  copy: src=metrics.rb dest=/etc/sensu/extensions/mutators/metrics.rb mode=0644
  notify: restart sensu server services
  when: use_grafana
