#base/taks/main/yml
---

- name: Remove default Gem source HTTP
  command: gem sources -r http://rubygems.org/

- name: Add new Gem source HTTPS
  command: gem sources -a https://rubygems.org/

- name: Install RabbitMQ signing key
  apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present
  
- name: Install sensu repository
  apt_repository: repo='deb     http://repos.sensuapp.org/apt sensu main' state=present

- name: Install sensu
  apt: name=sensu state=latest

- name: Create ssl directory
  file: state=directory path=/etc/sensu/ssl

- name: Copy over sensu SSL key (do not check this in)
  copy: src={{ item }} dest=/etc/sensu/ssl/{{ item }}
  with_items:
    - key.pem
    - cert.pem

- name: Template over rabbit connector config
  template: src=rabbitmq.json.j2 dest=/etc/sensu/conf.d/rabbitmq.json
  # Only the sensu client needs to be restarted
  notify: restart sensu-client
  
- name: Template over embedded ruby config
  template: src=sensu.j2 dest=/etc/default/sensu
  
- name: Add sensu to sudoers
  lineinfile:
    "dest=/etc/sudoers
    state=present
    regexp='^sensu ALL'
    validate='visudo -cf %s'
    line='sensu ALL=(ALL) NOPASSWD: ALL'"
  
