# client/tasks/main.yml
---
- name: Template over sensu config
  template: src=client.json.j2 dest=/etc/sensu/conf.d/client.json
  notify: restart sensu-client

- name: Install rubygems
  apt: name=rubygems state=latest
  when: ansible_distribution_release == "precise"

- name: Install sysstat
  apt: name=sysstat state=latest

- name: Enable sysstat to collect data
  lineinfile:
    dest=/etc/default/sysstat
    state=present
    regexp='^ENABLED="false"'
    line='ENABLED="true"'

- name: Tell sysstat to collect data every min
  lineinfile:
    dest=/etc/cron.d/sysstat
    state=present
    regexp='^5-55/10'
    line='* * * * * root command -v debian-sa1 > /dev/null && debian-sa1 1 1'

- name: Install ruby
  apt: name=ruby state=latest
  when: ansible_distribution_release == "trusty"

- name: Install ruby-dev
  apt: name=ruby-dev state=latest

- name: Install packages needed to build sensu plugins
  apt: name={{ item }} state=present
  with_items:
  - build-essential
  - libpq-dev

- name: Remove default Gem source HTTP
  command: gem sources -r http://rubygems.org/

- name: Add new Gem source HTTPS
  command: gem sources -a https://rubygems.org/

- name: Install sensu-plugin gem
  gem: name=sensu-plugin state=latest user_install=no
  when: ansible_distribution_release == "precise"

#- name: Install gem sys-filesystem
#  gem: name=sys-filesystem state=latest user_install=no

- name: Install sensu plugins (and some of their dependencies)
  gem: name={{ item }} state=latest user_install=no
  with_items:
    - sys-filesystem
    - rake
    - bundler
    - pg
    - rest_client
    - sensu-plugins-postgres
    - sensu-plugins-rabbitmq
    - sensu-plugins-disk-checks
    - sensu-plugins-process-checks
    - sensu-plugins-load-checks
    - sensu-plugins-memory-checks
    - sensu-plugins-network-checks
    - sensu-plugins-io-checks
    - sensu-plugins-ntp
    - sensu-plugins-cpu-checks
    - sensu-plugins-filesystem-checks
    - sensu-plugins-disk-checks
  notify: restart sensu-client

- name: Template over check-seqware-running.sh
  template: src=check-seqware-running.json.j2 dest=/etc/sensu/plugins/check-seqware-running.sh mode=0755
  notify: restart sensu-client

- name: Template over check-seqware-jobs-duration.sh
  template: src=check-seqware-jobs-duration.json.j2 dest=/etc/sensu/plugins/check-seqware-jobs-duration.sh mode=0755
  notify: restart sensu-client

- name: Template over check-seqware-sanger-last-workflow-status.sh
  template: src=check-seqware-sanger-last-workflow-status.json.j2 dest=/etc/sensu/plugins/check-seqware-sanger-last-workflow-status.sh mode=0755
  notify: restart sensu-client

- name: Template over check-seqware-sanger-jobs-duration.sh
  template: src=check-seqware-sanger-jobs-duration.json.j2 dest=/etc/sensu/plugins/check-seqware-sanger-jobs-duration.sh mode=0755
  notify: restart sensu-client

- name: Copy over checks for Worker node
  copy: src={{ item }} dest=/etc/sensu/plugins/ mode=0755
  with_items:
     - check-docker-containers.sh
  #These checks should only go on worker nodes.
  when: "'arch3-worker' in {{ subscriptions }}"
  notify: restart sensu-client

- name: Activate client services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - sensu-client

- name: Add sensu user to docker group
  user: name=sensu groups=docker
  when: "'master' in group_names"
