# client/tasks/main.yml
---
- name: Template over sensu config
  template: src=client.json.j2 dest=/etc/sensu/conf.d/client.json
  notify: restart sensu-client

- name: Install rubygems
  apt: name=rubygems state=latest
  when: ansible_distribution_release == "precise"

- name: Install sysstat
  apt: name=sysstat state=latest

- name: Enable sysstat to collect data
  lineinfile:
    dest=/etc/default/sysstat
    state=present
    regexp='^ENABLED="false"'
    line='ENABLED="true"'

- name: Tell sysstat to collect data every min
  lineinfile:
    dest=/etc/cron.d/sysstat
    state=present
    regexp='^5-55/10'
    line='* * * * * root command -v debian-sa1 > /dev/null && debian-sa1 1 1'

- name: Install ruby
  apt: name=ruby state=latest
  when: ansible_distribution_release == "trusty"

- name: Remove default Gem source HTTP
  command: gem sources -r http://rubygems.org/

- name: Add new Gem source HTTPS
  command: gem sources -a https://rubygems.org/

- name: Install sensu-plugin gem
  gem: name=sensu-plugin state=latest
  when: ansible_distribution_release == "precise"

- name: Install check-procs plugin 
  get_url: 
    dest=/etc/sensu/plugins/check-procs.rb 
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/processes/check-procs.rb
    mode=755
  notify: restart sensu-client

- name: Install load metrics
  get_url: 
    dest=/etc/sensu/plugins/load-metrics.rb 
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/system/load-metrics.rb
    mode=755
  notify: restart sensu-client

- name: Install memory metrics
  get_url: 
    dest=/etc/sensu/plugins/memory-metrics.rb 
    url=https://raw.githubusercontent.com/sensu/sensu-community-plugins/master/plugins/system/memory-metrics.rb
    mode=755
  notify: restart sensu-client

- name: Install interface metrics
  get_url: 
    dest=/etc/sensu/plugins/interface-metrics.rb 
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/system/interface-metrics.rb
    mode=755
  notify: restart sensu-client

- name: Install disk metrics
  get_url: 
    dest=/etc/sensu/plugins/disk-usage-metrics.rb 
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/system/disk-usage-metrics.rb
    mode=755
  notify: restart sensu-client

- name: Install iostat metrics
  get_url: 
    dest=/etc/sensu/plugins/iostat-extended-metrics.rb
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/system/iostat-extended-metrics.rb
    mode=755
  notify: restart sensu-client

- name: Install check-ntp plugin 
  get_url: 
    dest=/etc/sensu/plugins/check-ntp.rb 
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/system/check-ntp.rb
    mode=755
  notify: restart sensu-client

  
- name: Install check-cmd plugin 
  get_url: 
    dest=/etc/sensu/plugins/check-cmd.rb 
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/processes/check-cmd.rb
    mode=755
  notify: restart sensu-client
  
- name: Install check-cpu plugin 
  get_url: 
    dest=/etc/sensu/plugins/check-cpu.rb 
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/system/check-cpu.rb
    mode=755
  notify: restart sensu-client

- name: Install check-fs-writable plugin 
  get_url: 
    dest=/etc/sensu/plugins/check-fs-writable.rb 
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/system/check-fs-writable.rb
    mode=755
  notify: restart sensu-client

- name: Install check-mem plugin 
  get_url: 
    dest=/etc/sensu/plugins/check-mem.sh 
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/system/check-mem.sh
    mode=755
  notify: restart sensu-client


- name: Install check-disk-capacity plugin 
  get_url: 
    dest=/etc/sensu/plugins/disk-capacity-metrics.rb
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/system/disk-capacity-metrics.rb
    mode=755
  notify: restart sensu-client


- name: Install check-disk plugin 
  get_url: 
    dest=/etc/sensu/plugins/check-disk.rb
    url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/system/check-disk.rb
    mode=755
  notify: restart sensu-client

- name: Template over check-seqware-running.sh
  template: src=check-seqware-running.json.j2 dest=/etc/sensu/plugins/check-seqware-running.sh mode=0755
  notify: restart sensu-client

- name: Template over check-seqware-jobs-duration.sh
  template: src=check-seqware-jobs-duration.json.j2 dest=/etc/sensu/plugins/check-seqware-jobs-duration.sh mode=0755
  notify: restart sensu-client

- name: Template over check-seqware-sanger-last-workflow-status.sh
  template: src=check-seqware-sanger-last-workflow-status.json.j2 dest=/etc/sensu/plugins/check-seqware-sanger-last-workflow-status.sh mode=0755
  notify: restart sensu-client

- name: Template over check-seqware-sanger-jobs-duration.sh
  template: src=check-seqware-sanger-jobs-duration.json.j2 dest=/etc/sensu/plugins/check-seqware-sanger-jobs-duration.sh mode=0755
  notify: restart sensu-client

- name: Copy over Gluster peer status check
  copy: src={{ item }} dest=/etc/sensu/plugins/ mode=0755
  with_items:
     - check-gluster.sh
     - check-qstat.sh
     - check-seqware-failed.sh
     - check-sanger.sh
     - check-sge-running-steps.sh
     - check-hdfs.sh
     - check-docker-containers.sh
  notify: restart sensu-client

- name: Activate client services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - sensu-client 

- name: Set up the oozie env variable
  copy: src=oozie.sh dest=/etc/profile.d/ mode=0755

- name: Check if Seqware is installed on this machine
  command: ls /home
  register: home_output

- name: Copy over the script that restarts oozie in case is out-of-sync with SGE
  copy: src=test_oozie_sge.pl  dest=/mnt/home/seqware mode=0755
  when: home_output.stdout.find('seqware') != -1

- name: Creates a cron job that runs every 30 min and executes the oozie restart script
  cron: name="restart oozie" minute="*/30" hour="*" user=seqware job="perl /mnt/home/seqware/test_oozie_sge.pl > /dev/null"
  when: home_output.stdout.find('seqware') != -1

- name: Add sensu user to docker group
  user: name=sensu groups=docker

